In [253]:
import pandas as pd
import numpy as np
import seaborn as sns
import requests
import matplotlib.pyplot as plt
from espn_api.baseball import League
from draft_scraper import get_draft_strategy, get_draft_details, historical_get_draft_details, get_team_info, get_player_info

combined_proj = pd.read_csv('combined_projections.csv')

In [254]:
year = 2022
league_id=55646
swid = '{8F5C0C75-0EC6-4CD4-9C0C-750EC64CD455}'
espn_s2 = 'AEBvIL4Dlefi3KlVW0JH87iCDbcx0707HaHAXb8P3MgYzjwJWCk1xxdv5Jx7tR0CBOFRNPNOwgz1%2BwcsidB7tbVivNai4urRBeT%2FzXT59InIGYVeI8KHVfwy1eHZmQy%2FS5MDXM8caPu0seOzHhRF7PpYibmzCnmRCN4OBxBDrUEioqe%2BJsL93wEsl6ElDWE8Ff8laLi4MLZUbN6gQ1jFiCYdqwbmAOfCPIK%2Fe%2FnVRRdIoI5jpK82fUujjmoDqqkDj%2BTRTERwvpxvTx49B%2F3FKZCj9GzKr3N8dh46X%2FUermxajA%3D%3D'
'https://fantasy.espn.com/apis/v3/games/flb/seasons/2022/segments/0/leagues/55646?view=mDraftDetail&view=mSettings&view=mTeam&view=modular&view=mNav'
espn_cookies = {'swid': '{8F5C0C75-0EC6-4CD4-9C0C-750EC64CD455}',
 'espn_s2': 'AEBvIL4Dlefi3KlVW0JH87iCDbcx0707HaHAXb8P3MgYzjwJWCk1xxdv5Jx7tR0CBOFRNPNOwgz1%2BwcsidB7tbVivNai4urRBeT%2FzXT59InIGYVeI8KHVfwy1eHZmQy%2FS5MDXM8caPu0seOzHhRF7PpYibmzCnmRCN4OBxBDrUEioqe%2BJsL93wEsl6ElDWE8Ff8laLi4MLZUbN6gQ1jFiCYdqwbmAOfCPIK%2Fe%2FnVRRdIoI5jpK82fUujjmoDqqkDj%2BTRTERwvpxvTx49B%2F3FKZCj9GzKr3N8dh46X%2FUermxajA%3D%3D'}

custom_headers_2 = {
 'Connection': 'keep-alive',
 'Accept': 'application/json, text/plain, */*',
 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
 'x-fantasy-filter': '{"players":{"filterStatsForSplitTypeIds":{"value":[0]},"filterStatsForSourceIds":{"value":[1]},"filterStatsForExternalIds":{"value":[2023]},"sortDraftRanks":{"sortPriority":2,"sortAsc":true,"value":"STANDARD"},"sortPercOwned":{"sortPriority":3,"sortAsc":false},"filterStatsForTopScoringPeriodIds":{"value":5,"additionalValue":["002023","102023","002022","012023","022023","032023","042023","062023","010002023"]}}}',
 'x-fantasy-platform': 'kona-PROD-ee68d9ab1a30c5c961b9d2c47cb84c8f1ce2bd94',
 'x-fantasy-source': 'kona'
}

custom_headers = {
 'Connection': 'keep-alive',
 'Accept': 'application/json, text/plain, */*',
 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
 'x-fantasy-filter': '{"filterActive":null}',
 'x-fantasy-platform': 'kona-PROD-1dc40132dc2070ef47881dc95b633e62cebc9913',
 'x-fantasy-source': 'kona'
}

headers = {
 'Connection': 'keep-alive',
 'Accept': 'application/json, text/plain, */*',
 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
}

team_names = {'team_id':[1, 2, 3, 4, 5, 6, 7, 9, 10, 11], 'manager_name':['Jake', 'Brent', 'Cuyler', 'Dakota', 'Korn',
'Alex', 'John', 'Alden', 'Will', 'Kerry']}
team_name_df = pd.DataFrame.from_dict(team_names)

In [255]:
# Check if 2022 and 2023 are the same -- they look very similar
get_draft_strategy(2022).loc[((get_draft_strategy(2022) != get_draft_strategy(2023)).iloc[:, 0])]

           id  pre_draft_ranking
6       33039                  7
7       28976                  8
8       30193                  9
9       37515                 10
10      30951                 11
...       ...                ...
2995    41708               3905
2996    42543               3906
2997  4905919               3909
2998    39927               3910
2999  4684430               3912

[2992 rows x 2 columns]

In [256]:
d_2023 = get_draft_details(league_id=league_id, season_id=2023)

In [257]:
d_2023

     overallPickNumber  playerId  teamId
0                    1     30193      11
1                    2     32833       2
2                    3     33859       6
3                    4     32146       4
4                    5     28976       5
..                 ...       ...     ...
295                296     34967      10
296                297     32691       1
297                298     32081       3
298                299     33172       9
299                300     31187       7

[300 rows x 3 columns]

In [233]:
# Draft data (actual)
d_2018 = historical_get_draft_details(league_id=league_id, season_id=2018)
d_2019 = historical_get_draft_details(league_id=league_id, season_id=2019)
d_2020 = historical_get_draft_details(league_id=league_id, season_id=2020)
d_2021 = historical_get_draft_details(league_id=league_id, season_id=2021)
d_2022 = historical_get_draft_details(league_id=league_id, season_id=2022)
d_2022 = historical_get_draft_details(league_id=league_id, season_id=2022)

d_2018['year'] = '2018'
d_2019['year'] = '2019'
d_2020['year'] = '2020'
d_2021['year'] = '2021'
d_2022['year'] = '2022'

# Pre draft data
pre_2018 = get_draft_strategy(2018)
pre_2019 = get_draft_strategy(2019)
pre_2020 = get_draft_strategy(2020)
pre_2021 = get_draft_strategy(2021)
pre_2022 = get_draft_strategy(2022)

# Player data
pl_2018 = get_player_info('2018')
pl_2019 = get_player_info('2019')
pl_2020 = get_player_info('2020')
pl_2021 = get_player_info('2021')
pl_2022 = get_player_info('2022')

#Player team data
pltm_2018 = get_team_info('2018')
pltm_2019 = get_team_info('2019')
pltm_2020 = get_team_info('2020')
pltm_2021 = get_team_info('2021')
pltm_2022 = get_team_info('2022')

# Merge the data frames
d_n_pre_d_18 = pd.merge(d_2018, pre_2018, left_on = 'playerId', right_on='id', how = 'left')
full_p_18 = pd.merge(pl_2018, pltm_2018[['team_id', 'team name']], left_on='proTeamId', right_on = 'team_id', how='left')
draft_res_18 = pd.merge(d_n_pre_d_18, full_p_18[['eligibleSlots', 'defaultPositionId', 'fullName', 'player_id', 'team name']], left_on='playerId', right_on = 'player_id', how='left')
af_draft_18 = pd.merge(draft_res_18, team_name_df, left_on='teamId', right_on = 'team_id', how='left')
final_draft_18 = pd.concat([af_draft_18, pd.get_dummies(af_draft_18.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)


d_n_pre_d_19 = pd.merge(d_2019, pre_2019, left_on = 'playerId', right_on='id', how = 'left')
full_p_19 = pd.merge(pl_2019, pltm_2019[['team_id', 'team name']], left_on='proTeamId', right_on = 'team_id', how='left')
draft_res_19 = pd.merge(d_n_pre_d_19, full_p_19[['eligibleSlots', 'defaultPositionId', 'fullName', 'player_id', 'team name']], left_on='playerId', right_on = 'player_id', how='left')
af_draft_19 = pd.merge(draft_res_19, team_name_df, left_on='teamId', right_on = 'team_id', how='left')
final_draft_19 = pd.concat([af_draft_19, pd.get_dummies(af_draft_19.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)

d_n_pre_d_20 = pd.merge(d_2020, pre_2020, left_on = 'playerId', right_on='id', how = 'left')
full_p_20 = pd.merge(pl_2020, pltm_2020[['team_id', 'team name']], left_on='proTeamId', right_on = 'team_id', how='left')
draft_res_20 = pd.merge(d_n_pre_d_20, full_p_20[['eligibleSlots', 'defaultPositionId', 'fullName', 'player_id', 'team name']], left_on='playerId', right_on = 'player_id', how='left')
af_draft_20 = pd.merge(draft_res_20, team_name_df, left_on='teamId', right_on = 'team_id', how='left')
final_draft_20 = pd.concat([af_draft_20, pd.get_dummies(af_draft_20.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)

d_n_pre_d_21 = pd.merge(d_2021, pre_2021, left_on = 'playerId', right_on='id', how = 'left')
full_p_21 = pd.merge(pl_2021, pltm_2021[['team_id', 'team name']], left_on='proTeamId', right_on = 'team_id', how='left')
draft_res_21 = pd.merge(d_n_pre_d_21, full_p_21[['eligibleSlots', 'defaultPositionId', 'fullName', 'player_id', 'team name']], left_on='playerId', right_on = 'player_id', how='left')
af_draft_21 = pd.merge(draft_res_21, team_name_df, left_on='teamId', right_on = 'team_id', how='left')
final_draft_21 = pd.concat([af_draft_21, pd.get_dummies(af_draft_21.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)

d_n_pre_d_22 = pd.merge(d_2022, pre_2022, left_on = 'playerId', right_on='id', how = 'left')
full_p_22 = pd.merge(pl_2022, pltm_2022[['team_id', 'team name']], left_on='proTeamId', right_on = 'team_id', how='left')
draft_res_22 = pd.merge(d_n_pre_d_22, full_p_22[['eligibleSlots', 'defaultPositionId', 'fullName', 'player_id', 'team name']], left_on='playerId', right_on = 'player_id', how='left')
af_draft_22 = pd.merge(draft_res_22, team_name_df, left_on='teamId', right_on = 'team_id', how='left')
final_draft_22 = pd.concat([af_draft_22, pd.get_dummies(af_draft_22.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)

# Past owners
# 2018: Devyn Shaver, Team 5; Brent Backlund, Team 11
# 2019: Kerry replaces Brent Backlund for Team 11
# 2020: Korn replaces Devyn for Team 5

/var/folders/64/kktgr_017td3vw1nnvpfz4hw0000gn/T/ipykernel_86534/1836916241.py:40: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  final_draft_18 = pd.concat([af_draft_18, pd.get_dummies(af_draft_18.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)
/var/folders/64/kktgr_017td3vw1nnvpfz4hw0000gn/T/ipykernel_86534/1836916241.py:47: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  final_draft_19 = pd.concat([af_draft_19, pd.get_dummies(af_draft_19.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)
/var/folders/64/kktgr_017td3vw1nnvpfz4hw0000gn/T/ipykernel_86534/1836916241.py:53: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  final_draft_20 = pd.concat([af_draft_20, pd.get_dummies(af_draft_20.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)
/var/folders/64/kktgr_017td3vw1nnvpfz4hw0000gn/T/ipykernel_86534/1836916241.py:59: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  final_draft_21 = pd.concat([af_draft_21, pd.get_dummies(af_draft_21.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)
/var/folders/64/kktgr_017td3vw1nnvpfz4hw0000gn/T/ipykernel_86534/1836916241.py:65: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  final_draft_22 = pd.concat([af_draft_22, pd.get_dummies(af_draft_22.eligibleSlots.apply(pd.Series).stack()).sum(level=0)], axis = 1)

In [234]:
final = pd.concat([final_draft_20, final_draft_21, final_draft_22])

In [235]:
# combined_proj['ESPNID'] = combined_proj['ESPNID'].astype(int)
final['playerId'] = final['playerId'].astype(int)
final['year'] = final['year'].astype(int)

In [236]:
combined_proj

,Unnamed: 0,playerid,Name,pr,adp,R,HR,RBI,RC,AVG,OPS,IP,SO,QS,ERA,WHIP,SVHD,Year,ESPNID,ESPNNAME
0,1,10155,Mike Trout,14.627936,1.0,2.039515,2.457341,1.689529,2.578647,2.009931,3.852972,NaN,NaN,NaN,NaN,NaN,NaN,2020,30836.0,Mike Trout
1,2,15998,Cody Bellinger,14.374388,4.0,2.330820,2.727159,2.368676,2.587152,1.548722,2.811860,NaN,NaN,NaN,NaN,NaN,NaN,2020,33912.0,Cody Bellinger
2,3,11477,Christian Yelich,14.187018,3.0,2.136617,2.187524,2.077613,2.632794,2.303429,2.849042,NaN,NaN,NaN,NaN,NaN,NaN,2020,31283.0,Christian Yelich
3,4,20123,Juan Soto,13.797115,9.0,2.136617,2.187524,2.271655,2.705462,1.758362,2.737495,NaN,NaN,NaN,NaN,NaN,NaN,2020,36969.0,Juan Soto
4,5,6184,J.D. Martinez,13.429864,16.0,1.748210,2.457341,2.271655,2.386399,2.051860,2.514399,NaN,NaN,NaN,NaN,NaN,NaN,2020,31065.0,J.D. Martinez
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3403,3404,11470,Tony Wolters,-8.920980,NaN,-1.240777,-1.088182,-1.214413,-1.201011,-1.657276,-2.519321,NaN,NaN,NaN,NaN,NaN,NaN,2022,31844.0,Tony Wolters
3404,3405,15104,Jothan Davis,-9.177640,NaN,-1.206343,-1.088182,-1.214413,-1.180063,-2.199294,-2.289346,NaN,NaN,NaN,NaN,NaN,NaN,2022,38161.0,Jonathan Davis
3405,3406,13167,Robel García,-9.368275,NaN,-1.240777,-0.987648,-1.214413,-1.187585,-2.921985,-1.815866,NaN,NaN,NaN,NaN,NaN,NaN,2022,33451.0,Robel Garcia
3406,3407,3411,Drew Butera,-9.751163,NaN,-1.206343,-0.987648,-1.179503,-1.166563,-2.786481,-2.424626,NaN,NaN,NaN,NaN,NaN,NaN,2022,29436.0,Drew Butera
3407,3408,2539,Pete Kozma,-9.990376,NaN,-1.206343,-1.088182,-1.214413,-1.185479,-2.289630,-3.006329,NaN,NaN,NaN,NaN,NaN,NaN,2022,30011.0,Pete Kozma

In [237]:
joined = pd.merge(final, combined_proj, left_on = ['playerId', 'year'], right_on=['ESPNID', 'Year'], how = 'left')
joined['Year'] = joined.Year.astype('str')
joined['playerid'] = joined.playerid.astype('str')

In [238]:
joined.set_index('playerId')
joined.columns

Index(['overallPickNumber', 'playerId', 'teamId', 'year', 'id',
       'pre_draft_ranking', 'eligibleSlots', 'defaultPositionId', 'fullName',
       'player_id', 'team name', 'team_id', 'manager_name', '1B', '1B/3B',
       '2B', '2B/SS', '3B', 'C', 'CF', 'DH', 'LF', 'OF', 'RF', 'RP', 'SP',
       'SS', 'Unnamed: 0', 'playerid', 'Name', 'pr', 'adp', 'R', 'HR', 'RBI',
       'RC', 'AVG', 'OPS', 'IP', 'SO', 'QS', 'ERA', 'WHIP', 'SVHD', 'Year',
       'ESPNID', 'ESPNNAME'],
      dtype='object')

# Now on to the fun stuff: modeling

In [240]:
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.model_selection import train_test_split

In [242]:

labels = joined['overallPickNumber']
# Remove the labels from the features
# axis 1 refers to the columns
#features= joined.drop(['overallPickNumber', 'Unnamed: 0', 'ESPNNAME', 'ESPNID', 'fullName', 'team name', 'player_id'], axis = 1)
features = joined[['overallPickNumber', 'pre_draft_ranking', 'team_id', 'pr', 'SP', 'RP', 'HR', 'RC', 'R', 'IP', 'QS']]
# Saving feature names for later use
feature_list = ['pre_draft_ranking','team_id', 'pr', 'SP', 'RP', 'HR', 'RC', 'R', 'IP', 'QS']

In [243]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25)

In [244]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (676, 11)
Training Labels Shape: (676,)
Testing Features Shape: (226, 11)
Testing Labels Shape: (226,)

In [245]:
train_features

,overallPickNumber,pre_draft_ranking,team_id,pr,SP,RP,HR,RC,R,IP,QS
134,135,162,11,4.226233,0,0,0.298802,0.791964,1.359803,NaN,NaN
365,66,75,11,9.627019,0,0,1.590724,1.893564,1.657900,NaN,NaN
698,98,138,3,9.474213,0,0,2.430514,1.579897,1.307331,NaN,NaN
672,72,25,2,11.515222,1,0,NaN,NaN,NaN,2.839841,2.643592
594,295,322,11,0.273447,0,0,0.348827,0.121095,0.220508,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
596,297,111,3,14.886003,1,0,NaN,NaN,NaN,2.724739,2.615843
674,74,129,4,6.694369,0,0,1.224104,1.096399,1.031860,NaN,NaN
582,283,563,6,1.634773,0,0,0.059051,0.432470,0.534253,NaN,NaN
753,153,67,6,9.118436,1,0,NaN,NaN,NaN,2.537187,2.707777
31,32,15,7,8.560697,0,0,1.108254,1.343426,1.456905,NaN,NaN

In [246]:
# Instantiate model with 1000 decision trees
hbg = HistGradientBoostingRegressor()
# Train the model on training data
est = hbg.fit(train_features, train_labels)

In [247]:
# Use the forest's predict method on the test data
predictions = hbg.predict(test_features)
# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'picks.')

Mean Absolute Error: 0.67 picks.

In [248]:
from sklearn.model_selection import cross_val_score
from sklearn import metrics
def modelfit(alg, predictor_df, predictors, label_var, performCV=True, printFeatureImportance=True, cv_folds=5):
    #Fit the algorithm on the data
    alg.fit(predictor_df[predictors], predictor_df[label_var])
        
    #Predict training set:
    dtrain_predictions = alg.predict(predictor_df[predictors])
    # dtrain_predprob = alg.predict_proba(predictor_df[predictors])[:,1]
    
    #Perform cross-validation:
    if performCV:
        cv_score = cross_val_score(alg, predictor_df[predictors], predictor_df[label_var], cv=cv_folds, scoring='neg_root_mean_squared_error')
    
    #Print model report:
    print ("\nModel Report")
    print ("MSE : %.4g" % metrics.mean_squared_error(predictor_df[label_var].values, dtrain_predictions))
    #print ("AUC Score (Train): %f" % metrics.roc_auc_score(predictor_df[label_var], dtrain_predprob))
    
    if performCV:
        print ("CV Score : Mean - %.7g | Std - %.7g | Min - %.7g | Max - %.7g" % (np.mean(cv_score),np.std(cv_score),np.min(cv_score),np.max(cv_score)))
        
    #Print Feature Importance:
    if printFeatureImportance:
        feat_imp = pd.Series(alg.feature_importances_, predictors).sort_values(ascending=False)
        feat_imp.plot(kind='bar', title='Feature Importances')
        plt.ylabel('Feature Importance Score')

In [249]:
modelfit(hbg, features, feature_list, label_var = 'overallPickNumber', printFeatureImportance=False)

Model Report
MSE : 765.1
CV Score : Mean - -73.33882 | Std - 10.74491 | Min - -86.52363 | Max - -53.7974

In [219]:
predictors

,overallPickNumber,pre_draft_ranking,team_id,pr,SP,RP,adp,HR,RC,R,IP,QS
0,1,11,3,14.374388,0,0,4.0,2.727159,2.587152,2.330820,NaN,NaN
1,2,21,7,10.058810,0,0,36.0,1.378071,1.881973,1.651108,NaN,NaN
2,3,167,4,8.003180,1,0,70.0,0.838437,0.822953,0.680091,0.100461,0.332981
3,4,5,1,11.110406,0,0,17.0,1.647889,1.970017,1.456905,NaN,NaN
4,5,33,11,11.773411,0,0,22.0,1.917706,2.028508,2.136617,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
897,296,13,10,11.581312,0,0,16.0,2.128912,1.973321,1.686104,NaN,NaN
898,297,57,1,10.127577,0,0,37.0,1.324638,1.739637,1.445067,NaN,NaN
899,298,3,3,15.065993,1,0,4.0,NaN,NaN,NaN,2.818223,4.077059
900,299,51,9,10.098979,0,0,53.0,1.525707,1.918648,1.789406,NaN,NaN
901,300,54,7,11.450714,0,0,47.0,2.128912,1.960791,1.892708,NaN,NaN

In [220]:
from sklearn.model_selection import GridSearchCV
#Choose all predictors except target & IDcols
predictors = joined[['overallPickNumber', 'pre_draft_ranking','team_id', 'pr', 'SP', 'RP', 'adp', 'HR', 'RC', 'R', 'IP', 'QS']]
train_features, test_features, train_labels, test_labels = train_test_split(predictors, labels, test_size = 0.25, random_state = 42)
hbg = HistGradientBoostingRegressor()
param_grid = {
    'learning_rate': (0.01, 0.1, 1, 10),
    'max_leaf_nodes': (3, 10, 30)}
model_grid_search = GridSearchCV(hbg, param_grid=param_grid,
                                 n_jobs=2, cv=5)
model_grid_search.fit(train_features, train_labels)

GridSearchCV(cv=5, estimator=HistGradientBoostingRegressor(), n_jobs=2,
             param_grid={'learning_rate': (0.01, 0.1, 1, 10),
                         'max_leaf_nodes': (3, 10, 30)})

In [221]:
accuracy = model_grid_search.score(test_features, test_labels)
print(
    f"The test accuracy score of the grid-searched pipeline is: "
    f"{accuracy:.2f}"
)

The test accuracy score of the grid-searched pipeline is: 1.00

In [222]:
cv_results = pd.DataFrame(model_grid_search.cv_results_).sort_values(
    "mean_test_score", ascending=False)
cv_results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_leaf_nodes,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
5,1.379160,0.023706,0.016507,0.001211,0.1,30,"{'learning_rate': 0.1, 'max_leaf_nodes': 30}",0.999822,0.999709,0.999796,0.999858,0.999784,0.999794,0.000050,1
4,0.792216,0.009299,0.013430,0.001602,0.1,10,"{'learning_rate': 0.1, 'max_leaf_nodes': 10}",0.999781,0.999678,0.999752,0.999831,0.999740,0.999756,0.000050,2
3,0.205962,0.016518,0.014753,0.001281,0.1,3,"{'learning_rate': 0.1, 'max_leaf_nodes': 3}",0.999341,0.999388,0.999507,0.999438,0.999423,0.999419,0.000055,3
6,0.200806,0.007265,0.014900,0.001158,1,3,"{'learning_rate': 1, 'max_leaf_nodes': 3}",0.998502,0.998267,0.998553,0.998074,0.997971,0.998274,0.000229,4
7,0.726294,0.023078,0.015781,0.001537,1,10,"{'learning_rate': 1, 'max_leaf_nodes': 10}",0.995511,0.997761,0.998166,0.995540,0.997796,0.996955,0.001175,5

In [223]:
predictors.columns

Index(['overallPickNumber', 'pre_draft_ranking', 'team_id', 'pr', 'SP', 'RP',
       'adp', 'HR', 'RC', 'R', 'IP', 'QS'],
      dtype='object')

In [224]:
modelfit(model_grid_search.best_estimator_, predictors, predictors.columns, label_var = 'overallPickNumber', printFeatureImportance=False)

Model Report
MSE : 0.1495
CV Score : Mean - -0.8621314 | Std - 0.2747487 | Min - -1.186025 | Max - -0.4061193

# Predict on new data